# -*- coding: utf-8 -*-
"""Lab Cycle 1_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uh-oCIAGZqTtUnATRTVaajFzmK8D_gxv

#**Python - Lab Cycle - 1**

**1. Develop a program to read a four-digit number and find its**
\
a. Sum of digits\
b. Reverse\
c. Difference between the product of digits at the odd position
and the product of digits at the even position.
"""

num = int(input("Enter a four digit number : "))
#initialising the numbers with 0 , to add the sum of digits and reverse number to it
sum = 0
reverse = 0

#extracting each digits into variables digit_1 to digit_4 respectively
digit_4 = num%10
num = num//10
digit_3 = num%10
num = num//10
digit_2 = num%10
num = num//10
digit_1 = num%10
num = num//10

#sum of each digits stored to variable sum
sum = digit_1 + digit_2 + digit_3 + digit_4

#reverse of the number stored to variable reverse
reverse = (digit_4*1000) + (digit_3*100) + (digit_2*10) + digit_1

#product of digits at odd positions are stored to product_of_odd
product_of_odd = digit_1*digit_3
#product of digits at even positions are stored to product_of_even
product_of_even = digit_2*digit_4
#the difference of product of odd and even is stored to difference
difference = product_of_odd - product_of_even 

print("The sum is ",sum)
print("The difference is ",difference)
print("The reverse is ",reverse)