# -*- coding: utf-8 -*-
"""Lab Cycle 1_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sqKV7VFIGO_9LIYhoWUlABfoZW98-kTh

#**Python - Lab Cycle - 1**

**2. Develop a program to read the three sides of two triangles and calculate the area of both. Define a function to read the three sides and call it. Also, define a function to calculate the area. Print the total area enclosed by both triangles and each triangle's contribution (%) towards it.**
"""

#function - to get the sides from the user
def get_sides():
  a = float(input("Enter the side A :"))
  b = float(input("Enter the side B :"))
  c = float(input("Enter the side C :"))
  return a,b,c

#function - to calculate the area of the triangle
def calculate_area(a,b,c):
  s = (a+b+c)/2
  area = (s*(s-a)*(s-b)*(s-c))**(1/2)
  return area

print("For the First Triangle")
a1,b1,c1 = get_sides()
area_1 = calculate_area(a1,b1,c1)
print("The area of first triangle is ",area_1)

print("For the Second Triangle")
a2,b2,c2 = get_sides()
area_2 = calculate_area(a2,b2,c2)
print("The area of second triangle is ",area_2)

#total area calculation
total_area = area_1 + area_2
#calculating the contribution of each triangle to area
contribution_of_triangle1 = (100*area_1)/total_area
contribution_of_triangle2 = (100*area_2)/total_area

print("The total area is ",total_area)
print("The % contribution of triangle 1 to total area is ",contribution_of_triangle1,"%")
print("The % contribution of triangle 2 to total area is ",contribution_of_triangle2,"%")